namespace Blueprint.Languages.Adapaters.Actipro.BlueLang {
    using ActiproSoftware.Text;
    using ActiproSoftware.Text.Implementation;
    using ActiproSoftware.Text.Lexing;
    
    
    /// <summary>
    /// Represents a <c>Blue print</c> syntax language definition.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v24.1.1.0 (http://www.actiprosoftware.com).
    /// Generated code is based on input created by Blueprint.
    /// Blueprint
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("LanguageDesigner", "24.1.1.0")]
    public partial class BlueSyntaxLanguage : SyntaxLanguage {
        
        /// <summary>
        /// Initializes a new instance of the <c>BlueSyntaxLanguage</c> class.
        /// </summary>
        public BlueSyntaxLanguage() : 
                base("Blue print") {

            // Create a classification type provider and register its classification types
            BlueClassificationTypeProvider classificationTypeProvider = new BlueClassificationTypeProvider();
            classificationTypeProvider.RegisterAll();

            // Register an ILexer service that can tokenize text
            this.RegisterService<ILexer>(new BlueLexer(classificationTypeProvider));

            // Register an ICodeDocumentTaggerProvider service that creates a token tagger for
            //   each document using the language
            this.RegisterService(new BlueTokenTaggerProvider(classificationTypeProvider));

            // Register an IExampleTextProvider service that provides example text
            this.RegisterService<IExampleTextProvider>(new BlueExampleTextProvider());
        }
    }
}
