namespace Blueprint.Languages.Adapaters.Actipro.BlueLang {
    using ActiproSoftware.Text;
    using System;
    
    
    /// <summary>
    /// Represents a example text provider for the <c>Blue print</c> language.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v24.1.1.0 (http://www.actiprosoftware.com).
    /// Generated code is based on input created by Blueprint.
    /// Blueprint
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("LanguageDesigner", "24.1.1.0")]
    public partial class BlueExampleTextProvider : Object, IExampleTextProvider {
        
        /// <summary>
        /// Gets the example text, a code snippet of the related language.
        /// </summary>
        /// <value>The example text, a code snippet of the related language.</value>
        public String ExampleText {
            get {
                return @"resource Customer
{
    key Id: Guid

    required FirstName: string max(100)
    required LastName: string max(100)
    required Email: string max(200)

    active: bool = true

    rules
    {
        FirstName notEmpty
        LastName notEmpty
        Email notEmpty
        Email isEmail
    }
}

request CreateCustomerDto  (Customer c) =>
{
    FirstName,
    LastName,
    Email
}

response CustomerDto ( Customer c ) => 
{
    Id,
    Name => $""{FirstName} 
	this also allow you to put anything you'd like {LastName}"",
    Email
    Active
}


controller Customers at ""/api/customers""
{
    post ""/""
    {
        input: CreateCustomerDto
        output: CustomerDto
    }

	// comment
    get ""/{id}""
    {
        input: id
        output: CustomerDto
    }
}";
            }
        }
    }
}
