namespace Blueprint.Languages.Adapaters.Actipro.BlueLang {
    using ActiproSoftware.Text;
    using ActiproSoftware.Text.Tagging.Implementation;
    using System;
    
    
    /// <summary>
    /// Represents a token tagger for the <c>Blue print</c> language.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v24.1.1.0 (http://www.actiprosoftware.com).
    /// Generated code is based on input created by Blueprint.
    /// Blueprint
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("LanguageDesigner", "24.1.1.0")]
    public partial class BlueTokenTagger : TokenTagger {
        
        private IBlueClassificationTypeProvider classificationTypeProviderValue;
        
        /// <summary>
        /// Initializes a new instance of the <c>BlueTokenTagger</c> class.
        /// </summary>
        /// <param name="document">The specific <see cref="ICodeDocument"/> for which this token tagger will be used.</param>
        /// <param name="classificationTypeProvider">A <see cref="IBlueClassificationTypeProvider"/> that provides classification types used by this token tagger.</param>
        public BlueTokenTagger(ICodeDocument document, IBlueClassificationTypeProvider classificationTypeProvider) : 
                base(document) {
            if ((classificationTypeProvider == null)) {
                throw new ArgumentNullException("classificationTypeProvider");
            }

            // Initialize
            this.classificationTypeProviderValue = classificationTypeProvider;
        }
        
        /// <summary>
        /// Gets the <see cref="IBlueClassificationTypeProvider"/> that provides classification types used by this token tagger.
        /// </summary>
        /// <value>The <see cref="IBlueClassificationTypeProvider"/> that provides classification types used by this token tagger.</value>
        public IBlueClassificationTypeProvider ClassificationTypeProvider {
            get {
                return this.classificationTypeProviderValue;
            }
        }
    }
}
