namespace Blueprint.Languages.Adapaters.Actipro.BlueLang {
    using ActiproSoftware.Text;
    using ActiproSoftware.Text.Implementation;
    using ActiproSoftware.Windows.Controls.SyntaxEditor.Highlighting;
    using ActiproSoftware.Windows.Controls.SyntaxEditor.Highlighting.Implementation;
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;
    
    
    /// <summary>
    /// Represents a provider of <see cref="IClassificationType"/> objects for the <c>Blue print</c> language.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v24.1.1.0 (http://www.actiprosoftware.com).
    /// Generated code is based on input created by Blueprint.
    /// Blueprint
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("LanguageDesigner", "24.1.1.0")]
    public partial class BlueClassificationTypeProvider : IBlueClassificationTypeProvider {
        
        private IHighlightingStyleRegistry registryValue;
        
        private IClassificationType brackets01Value;
        
        private IClassificationType brackets02Value;
        
        private IClassificationType brackets03Value;
        
        private IClassificationType columnValue;
        
        private IClassificationType commentValue;
        
        private IClassificationType delimiterValue;
        
        private IClassificationType identifierValue;
        
        private IClassificationType interpolatedStringDelimiterValue;
        
        private IClassificationType keywordValue;
        
        private IClassificationType numberValue;
        
        private IClassificationType parenthesisValue;
        
        private IClassificationType stringValue;
        
        /// <summary>
        /// Initializes a new instance of the <c>BlueClassificationTypeProvider</c> class.
        /// </summary>
        public BlueClassificationTypeProvider() : 
                this(null) {
        }
        
        /// <summary>
        /// Initializes a new instance of the <c>BlueClassificationTypeProvider</c> class.
        /// </summary>
        /// <param name="targetRegistry">The <see cref="IHighlightingStyleRegistry"/> to use when registering classification types and highlighting styles.</param>
        public BlueClassificationTypeProvider(IHighlightingStyleRegistry targetRegistry) {
            if ((targetRegistry != null)) {
                this.registryValue = targetRegistry;
            }
            else {
                this.registryValue = AmbientHighlightingStyleRegistry.Instance;
            }
        }
        
        /// <summary>
        /// Gets the <c>Brackets01</c> classification type.
        /// </summary>
        /// <value>The <c>Brackets01</c> classification type.</value>
        public IClassificationType Brackets01 {
            get {
                if ((this.brackets01Value == null)) {
                    String key = "Brackets01";
                    this.brackets01Value = this.registryValue.GetClassificationType(key);
                    if ((this.brackets01Value == null)) {
                        IHighlightingStyleColorPalette darkColorPalette = this.registryValue.DarkColorPalette;
                        if ((darkColorPalette != null)) {
                            darkColorPalette.SetForeground(key, Color.FromArgb(255, 255, 144, 0));
                        }
                        this.brackets01Value = new ClassificationType(key, "Brackets01");
                        this.registryValue.Register(this.brackets01Value, new HighlightingStyle(Color.FromArgb(255, 156, 14, 141)));
                    }
                }
                return this.brackets01Value;
            }
        }
        
        /// <summary>
        /// Gets the <c>Brackets02</c> classification type.
        /// </summary>
        /// <value>The <c>Brackets02</c> classification type.</value>
        public IClassificationType Brackets02 {
            get {
                if ((this.brackets02Value == null)) {
                    String key = "Brackets02";
                    this.brackets02Value = this.registryValue.GetClassificationType(key);
                    if ((this.brackets02Value == null)) {
                        IHighlightingStyleColorPalette darkColorPalette = this.registryValue.DarkColorPalette;
                        if ((darkColorPalette != null)) {
                            darkColorPalette.SetForeground(key, Color.FromArgb(255, 176, 159, 219));
                        }
                        this.brackets02Value = new ClassificationType(key, "Brackets02");
                        this.registryValue.Register(this.brackets02Value, new HighlightingStyle(Color.FromArgb(255, 156, 14, 141)));
                    }
                }
                return this.brackets02Value;
            }
        }
        
        /// <summary>
        /// Gets the <c>Brackets03</c> classification type.
        /// </summary>
        /// <value>The <c>Brackets03</c> classification type.</value>
        public IClassificationType Brackets03 {
            get {
                if ((this.brackets03Value == null)) {
                    String key = "Brackets03";
                    this.brackets03Value = this.registryValue.GetClassificationType(key);
                    if ((this.brackets03Value == null)) {
                        IHighlightingStyleColorPalette darkColorPalette = this.registryValue.DarkColorPalette;
                        if ((darkColorPalette != null)) {
                            darkColorPalette.SetForeground(key, Color.FromArgb(255, 229, 174, 198));
                        }
                        this.brackets03Value = new ClassificationType(key, "Brackets03");
                        this.registryValue.Register(this.brackets03Value, new HighlightingStyle(Color.FromArgb(255, 156, 14, 141)));
                    }
                }
                return this.brackets03Value;
            }
        }
        
        /// <summary>
        /// Gets the <c>Column</c> classification type.
        /// </summary>
        /// <value>The <c>Column</c> classification type.</value>
        public IClassificationType Column {
            get {
                if ((this.columnValue == null)) {
                    String key = "Column";
                    this.columnValue = this.registryValue.GetClassificationType(key);
                    if ((this.columnValue == null)) {
                        IHighlightingStyleColorPalette darkColorPalette = this.registryValue.DarkColorPalette;
                        if ((darkColorPalette != null)) {
                            darkColorPalette.SetForeground(key, Color.FromArgb(255, 233, 198, 57));
                        }
                        this.columnValue = new ClassificationType(key, "Column");
                        this.registryValue.Register(this.columnValue, new HighlightingStyle(Color.FromArgb(255, 149, 14, 173)));
                    }
                }
                return this.columnValue;
            }
        }
        
        /// <summary>
        /// Gets the <c>Comment</c> classification type.
        /// </summary>
        /// <value>The <c>Comment</c> classification type.</value>
        public IClassificationType Comment {
            get {
                if ((this.commentValue == null)) {
                    String key = "Comment";
                    this.commentValue = this.registryValue.GetClassificationType(key);
                    if ((this.commentValue == null)) {
                        IHighlightingStyleColorPalette darkColorPalette = this.registryValue.DarkColorPalette;
                        if ((darkColorPalette != null)) {
                            darkColorPalette.SetForeground(key, Color.FromArgb(255, 136, 196, 126));
                        }
                        this.commentValue = new ClassificationType(key, "Comment");
                        this.registryValue.Register(this.commentValue, new HighlightingStyle(Color.FromArgb(255, 0, 128, 0)));
                    }
                }
                return this.commentValue;
            }
        }
        
        /// <summary>
        /// Gets the <c>Delimiter</c> classification type.
        /// </summary>
        /// <value>The <c>Delimiter</c> classification type.</value>
        public IClassificationType Delimiter {
            get {
                if ((this.delimiterValue == null)) {
                    String key = "Delimiter";
                    this.delimiterValue = this.registryValue.GetClassificationType(key);
                    if ((this.delimiterValue == null)) {
                        this.delimiterValue = new ClassificationType(key, "Delimiter");
                        this.registryValue.Register(this.delimiterValue, new HighlightingStyle());
                    }
                }
                return this.delimiterValue;
            }
        }
        
        /// <summary>
        /// Gets the <c>Identifier</c> classification type.
        /// </summary>
        /// <value>The <c>Identifier</c> classification type.</value>
        public IClassificationType Identifier {
            get {
                if ((this.identifierValue == null)) {
                    String key = "Identifier";
                    this.identifierValue = this.registryValue.GetClassificationType(key);
                    if ((this.identifierValue == null)) {
                        IHighlightingStyleColorPalette darkColorPalette = this.registryValue.DarkColorPalette;
                        if ((darkColorPalette != null)) {
                            darkColorPalette.SetForeground(key, Color.FromArgb(255, 111, 206, 188));
                        }
                        this.identifierValue = new ClassificationType(key, "Identifier");
                        this.registryValue.Register(this.identifierValue, new HighlightingStyle(Color.FromArgb(255, 126, 104, 219)));
                    }
                }
                return this.identifierValue;
            }
        }
        
        /// <summary>
        /// Gets the <c>InterpolatedStringDelimiter</c> classification type.
        /// </summary>
        /// <value>The <c>InterpolatedStringDelimiter</c> classification type.</value>
        public IClassificationType InterpolatedStringDelimiter {
            get {
                if ((this.interpolatedStringDelimiterValue == null)) {
                    String key = "InterpolatedStringDelimiter";
                    this.interpolatedStringDelimiterValue = this.registryValue.GetClassificationType(key);
                    if ((this.interpolatedStringDelimiterValue == null)) {
                        IHighlightingStyleColorPalette darkColorPalette = this.registryValue.DarkColorPalette;
                        if ((darkColorPalette != null)) {
                            darkColorPalette.SetForeground(key, Color.FromArgb(255, 189, 141, 233));
                        }
                        this.interpolatedStringDelimiterValue = new ClassificationType(key, "InterpolatedStringDelimiter");
                        this.registryValue.Register(this.interpolatedStringDelimiterValue, new HighlightingStyle(Color.FromArgb(255, 214, 10, 129)));
                    }
                }
                return this.interpolatedStringDelimiterValue;
            }
        }
        
        /// <summary>
        /// Gets the <c>Keyword</c> classification type.
        /// </summary>
        /// <value>The <c>Keyword</c> classification type.</value>
        public IClassificationType Keyword {
            get {
                if ((this.keywordValue == null)) {
                    String key = "Keyword";
                    this.keywordValue = this.registryValue.GetClassificationType(key);
                    if ((this.keywordValue == null)) {
                        IHighlightingStyleColorPalette darkColorPalette = this.registryValue.DarkColorPalette;
                        if ((darkColorPalette != null)) {
                            darkColorPalette.SetForeground(key, Color.FromArgb(255, 122, 183, 233));
                        }
                        this.keywordValue = new ClassificationType(key, "Keyword");
                        this.registryValue.Register(this.keywordValue, new HighlightingStyle(Color.FromArgb(255, 14, 92, 156)));
                    }
                }
                return this.keywordValue;
            }
        }
        
        /// <summary>
        /// Gets the <c>Number</c> classification type.
        /// </summary>
        /// <value>The <c>Number</c> classification type.</value>
        public IClassificationType Number {
            get {
                if ((this.numberValue == null)) {
                    String key = "Number";
                    this.numberValue = this.registryValue.GetClassificationType(key);
                    if ((this.numberValue == null)) {
                        IHighlightingStyleColorPalette darkColorPalette = this.registryValue.DarkColorPalette;
                        if ((darkColorPalette != null)) {
                            darkColorPalette.SetForeground(key, Color.FromArgb(255, 181, 206, 168));
                        }
                        this.numberValue = new ClassificationType(key, "Number");
                        this.registryValue.Register(this.numberValue, new HighlightingStyle(Color.FromArgb(255, 115, 12, 12)));
                    }
                }
                return this.numberValue;
            }
        }
        
        /// <summary>
        /// Gets the <c>Parenthesis</c> classification type.
        /// </summary>
        /// <value>The <c>Parenthesis</c> classification type.</value>
        public IClassificationType Parenthesis {
            get {
                if ((this.parenthesisValue == null)) {
                    String key = "Parenthesis";
                    this.parenthesisValue = this.registryValue.GetClassificationType(key);
                    if ((this.parenthesisValue == null)) {
                        IHighlightingStyleColorPalette darkColorPalette = this.registryValue.DarkColorPalette;
                        if ((darkColorPalette != null)) {
                            darkColorPalette.SetForeground(key, Color.FromArgb(255, 233, 198, 57));
                        }
                        this.parenthesisValue = new ClassificationType(key, "Parenthesis");
                        this.registryValue.Register(this.parenthesisValue, new HighlightingStyle(Color.FromArgb(255, 76, 127, 9)));
                    }
                }
                return this.parenthesisValue;
            }
        }
        
        /// <summary>
        /// Gets the <c>String</c> classification type.
        /// </summary>
        /// <value>The <c>String</c> classification type.</value>
        public IClassificationType String {
            get {
                if ((this.stringValue == null)) {
                    String key = "String";
                    this.stringValue = this.registryValue.GetClassificationType(key);
                    if ((this.stringValue == null)) {
                        IHighlightingStyleColorPalette darkColorPalette = this.registryValue.DarkColorPalette;
                        if ((darkColorPalette != null)) {
                            darkColorPalette.SetForeground(key, Color.FromArgb(255, 214, 157, 133));
                        }
                        this.stringValue = new ClassificationType(key, "String");
                        this.registryValue.Register(this.stringValue, new HighlightingStyle(Color.FromArgb(255, 163, 21, 21)));
                    }
                }
                return this.stringValue;
            }
        }
        
        /// <summary>
        /// Gets the <see cref="IHighlightingStyleRegistry"/> to use when registering classification types and highlighting styles.
        /// </summary>
        /// <value>The <see cref="IHighlightingStyleRegistry"/> to use when registering classification types and highlighting styles.</value>
        public IHighlightingStyleRegistry Registry {
            get {
                return this.registryValue;
            }
        }
        
        /// <summary>
        /// Registers all classification types and highlighting styles with the <see cref="IHighlightingStyleRegistry"/> used by this class.
        /// </summary>
        /// <returns>The collection of <see cref="IClassificationType"/> objects that were registered.</returns>
        public IEnumerable<IClassificationType> RegisterAll() {
            return new IClassificationType[] {
                    Brackets01,
                    Brackets02,
                    Brackets03,
                    Column,
                    Comment,
                    Delimiter,
                    Identifier,
                    InterpolatedStringDelimiter,
                    Keyword,
                    Number,
                    Parenthesis,
                    String};
        }
    }
}
