namespace Blueprint.Languages.Adapaters.Actipro.BlueLang {
    using ActiproSoftware.Text;
    using ActiproSoftware.Text.Lexing.Implementation;
    using ActiproSoftware.Text.Utility;
    using System;
    
    
    /// <summary>
    /// Represents a lexer for the <c>Blue print</c> language.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v24.1.1.0 (http://www.actiprosoftware.com).
    /// Generated code is based on input created by Blueprint.
    /// Blueprint
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("LanguageDesigner", "24.1.1.0")]
    public partial class BlueLexer : DynamicLexer {
        
        /// <summary>
        /// Initializes a new instance of the <c>BlueLexer</c> class.
        /// </summary>
        /// <param name="classificationTypeProvider">A <see cref="IBlueClassificationTypeProvider"/> that provides classification types used by this lexer.</param>
        public BlueLexer(IBlueClassificationTypeProvider classificationTypeProvider) {
            if ((classificationTypeProvider == null)) {
                throw new ArgumentNullException("classificationTypeProvider");
            }

            // Create lexical states
            IKeyedObservableCollection<DynamicLexicalState> lexicalStates = ((IKeyedObservableCollection<DynamicLexicalState>)(this.LexicalStates));
            this.DefaultLexicalState.Id = BlueLexicalStateId.Default;
            lexicalStates.Add(new DynamicLexicalState(BlueLexicalStateId.InterpolatedStringContent, "InterpolatedStringContent"));
            lexicalStates.Add(new DynamicLexicalState(BlueLexicalStateId.PrimaryString, "PrimaryString"));
            lexicalStates.Add(new DynamicLexicalState(BlueLexicalStateId.InterpolatedString, "InterpolatedString"));
            lexicalStates.Add(new DynamicLexicalState(BlueLexicalStateId.SingleLineComment, "SingleLineComment"));
            lexicalStates.Add(new DynamicLexicalState(BlueLexicalStateId.MultiLineComment, "MultiLineComment"));

            DynamicLexicalState lexicalState = null;
            DynamicLexicalScope lexicalScope = null;
            DynamicLexicalPatternGroup lexicalPatternGroup = null;

            // Initialize the Default lexical state
            lexicalState = lexicalStates["Default"];
            lexicalState.ChildLexicalStates.Add(lexicalStates["PrimaryString"]);
            lexicalState.ChildLexicalStates.Add(lexicalStates["InterpolatedString"]);
            lexicalState.ChildLexicalStates.Add(lexicalStates["SingleLineComment"]);
            lexicalState.ChildLexicalStates.Add(lexicalStates["MultiLineComment"]);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "Whitespace", null);
            lexicalPatternGroup.TokenId = BlueTokenId.Whitespace;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("{Whitespace}+"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "LineTerminator", null);
            lexicalPatternGroup.TokenId = BlueTokenId.LineTerminator;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("{LineTerminator}"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "OpenParenthesis", classificationTypeProvider.Parenthesis);
            lexicalPatternGroup.TokenId = BlueTokenId.OpenParenthesis;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("("));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "CloseParenthesis", classificationTypeProvider.Parenthesis);
            lexicalPatternGroup.TokenId = BlueTokenId.CloseParenthesis;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern(")"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "Lambda", classificationTypeProvider.Parenthesis);
            lexicalPatternGroup.TokenId = BlueTokenId.Lambda;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("=>"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "EqualsSymbol", classificationTypeProvider.Column);
            lexicalPatternGroup.TokenId = BlueTokenId.EqualsSymbol;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("="));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "OpenCurlyBrace", classificationTypeProvider.Brackets);
            lexicalPatternGroup.TokenId = BlueTokenId.OpenCurlyBrace;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("{"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "CloseCurlyBrace", classificationTypeProvider.Brackets);
            lexicalPatternGroup.TokenId = BlueTokenId.CloseCurlyBrace;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("}"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "Keyword", classificationTypeProvider.Keyword);
            lexicalPatternGroup.TokenId = BlueTokenId.Keyword;
            lexicalPatternGroup.CaseSensitivity = CaseSensitivity.Sensitive;
            lexicalPatternGroup.LookBehindPattern = "{NonWord}|\\A";
            lexicalPatternGroup.LookAheadPattern = "{NonWord}|\\z";
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("at"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("bool"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("controller"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("key"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("max"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("request"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("required"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("resource"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("response"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("rules"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("string"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("notEmpty"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("isEmail"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("input"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("output"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("get"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("post"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("true"));
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("false"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "Column", classificationTypeProvider.Column);
            lexicalPatternGroup.TokenId = BlueTokenId.Column;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern(":"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "Identifier", classificationTypeProvider.Identifier);
            lexicalPatternGroup.TokenId = BlueTokenId.Identifier;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("(_ | {Alpha})({Word})*"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "RealNumber", classificationTypeProvider.Number);
            lexicalPatternGroup.TokenId = BlueTokenId.RealNumber;
            lexicalPatternGroup.LookAheadPattern = "{NonWord}|\\z";
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("{Digit}* \\. {Digit}+"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "IntegerNumber", classificationTypeProvider.Number);
            lexicalPatternGroup.TokenId = BlueTokenId.IntegerNumber;
            lexicalPatternGroup.LookAheadPattern = "{NonWord}|\\z";
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("{Digit}+"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);

            // Initialize the InterpolatedStringContent lexical state
            lexicalState = lexicalStates["InterpolatedStringContent"];
            lexicalScope = new DynamicLexicalScope();
            lexicalState.LexicalScopes.Add(lexicalScope);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, null, classificationTypeProvider.InterpolatedStringDelimiter);
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("{"));
            lexicalScope.StartLexicalPatternGroup = lexicalPatternGroup;
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, null, classificationTypeProvider.InterpolatedStringDelimiter);
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("}"));
            lexicalScope.EndLexicalPatternGroup = lexicalPatternGroup;
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "InterpolatedStringValue", classificationTypeProvider.Identifier);
            lexicalPatternGroup.TokenId = BlueTokenId.InterpolatedStringValue;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("[aA-zZ]+"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);

            // Initialize the PrimaryString lexical state
            lexicalState = lexicalStates["PrimaryString"];
            lexicalState.DefaultClassificationType = classificationTypeProvider.String;
            lexicalState.DefaultTokenId = BlueTokenId.PrimaryStringText;
            lexicalState.DefaultTokenKey = "PrimaryStringText";
            lexicalScope = new DynamicLexicalScope();
            lexicalState.LexicalScopes.Add(lexicalScope);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "PrimaryStringStartDelimiter", null);
            lexicalPatternGroup.TokenId = BlueTokenId.PrimaryStringStartDelimiter;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("\""));
            lexicalScope.StartLexicalPatternGroup = lexicalPatternGroup;
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "PrimaryStringEndDelimiter", null);
            lexicalPatternGroup.TokenId = BlueTokenId.PrimaryStringEndDelimiter;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("\""));
            lexicalScope.EndLexicalPatternGroup = lexicalPatternGroup;
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "PrimaryStringLineTerminator", null);
            lexicalPatternGroup.TokenId = BlueTokenId.PrimaryStringLineTerminator;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("\\n"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "PrimaryStringText", null);
            lexicalPatternGroup.TokenId = BlueTokenId.PrimaryStringText;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("[^\\{|\\\"\\n]+"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);

            // Initialize the InterpolatedString lexical state
            lexicalState = lexicalStates["InterpolatedString"];
            lexicalState.DefaultClassificationType = classificationTypeProvider.String;
            lexicalState.DefaultTokenId = BlueTokenId.PrimaryStringText;
            lexicalState.DefaultTokenKey = "PrimaryStringText";
            lexicalState.ChildLexicalStates.Add(lexicalStates["InterpolatedStringContent"]);
            lexicalScope = new DynamicLexicalScope();
            lexicalState.LexicalScopes.Add(lexicalScope);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "PrimaryStringStartDelimiter", null);
            lexicalPatternGroup.TokenId = BlueTokenId.PrimaryStringStartDelimiter;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("$\""));
            lexicalScope.StartLexicalPatternGroup = lexicalPatternGroup;
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "PrimaryStringEndDelimiter", null);
            lexicalPatternGroup.TokenId = BlueTokenId.PrimaryStringEndDelimiter;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("\""));
            lexicalScope.EndLexicalPatternGroup = lexicalPatternGroup;
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "PrimaryStringLineTerminator", null);
            lexicalPatternGroup.TokenId = BlueTokenId.PrimaryStringLineTerminator;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("\\n"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "PrimaryStringText", null);
            lexicalPatternGroup.TokenId = BlueTokenId.PrimaryStringText;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("[^\\{|\\\"\\n]+"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);

            // Initialize the SingleLineComment lexical state
            lexicalState = lexicalStates["SingleLineComment"];
            lexicalState.DefaultClassificationType = classificationTypeProvider.Comment;
            lexicalState.DefaultTokenId = BlueTokenId.SingleLineCommentText;
            lexicalState.DefaultTokenKey = "SingleLineCommentText";
            lexicalScope = new DynamicLexicalScope();
            lexicalState.LexicalScopes.Add(lexicalScope);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "SingleLineCommentStartDelimiter", null);
            lexicalPatternGroup.TokenId = BlueTokenId.SingleLineCommentStartDelimiter;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("//"));
            lexicalScope.StartLexicalPatternGroup = lexicalPatternGroup;
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "SingleLineCommentEndDelimiter", null);
            lexicalPatternGroup.TokenId = BlueTokenId.SingleLineCommentEndDelimiter;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("\\n"));
            lexicalScope.EndLexicalPatternGroup = lexicalPatternGroup;
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "SingleLineCommentText", null);
            lexicalPatternGroup.TokenId = BlueTokenId.SingleLineCommentText;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("[^\\n]+"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);

            // Initialize the MultiLineComment lexical state
            lexicalState = lexicalStates["MultiLineComment"];
            lexicalState.DefaultClassificationType = classificationTypeProvider.Comment;
            lexicalState.DefaultTokenId = BlueTokenId.MultiLineCommentText;
            lexicalState.DefaultTokenKey = "MultiLineCommentText";
            lexicalScope = new DynamicLexicalScope();
            lexicalState.LexicalScopes.Add(lexicalScope);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "MultiLineCommentStartDelimiter", null);
            lexicalPatternGroup.TokenId = BlueTokenId.MultiLineCommentStartDelimiter;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("/*"));
            lexicalScope.StartLexicalPatternGroup = lexicalPatternGroup;
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Explicit, "MultiLineCommentEndDelimiter", null);
            lexicalPatternGroup.TokenId = BlueTokenId.MultiLineCommentEndDelimiter;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("*/"));
            lexicalScope.EndLexicalPatternGroup = lexicalPatternGroup;
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "MultiLineCommentLineTerminator", null);
            lexicalPatternGroup.TokenId = BlueTokenId.MultiLineCommentLineTerminator;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("\\n"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
            lexicalPatternGroup = new DynamicLexicalPatternGroup(DynamicLexicalPatternType.Regex, "MultiLineCommentText", null);
            lexicalPatternGroup.TokenId = BlueTokenId.MultiLineCommentText;
            lexicalPatternGroup.Patterns.Add(new DynamicLexicalPattern("[^\\*\\n]+"));
            lexicalState.LexicalPatternGroups.Add(lexicalPatternGroup);
        }
    }
}
