namespace Blueprint.Languages.Adapaters.Actipro.BlueLang {
    using ActiproSoftware.Text;
    
    
    /// <summary>
    /// Provides the base requirements of an object that provides <see cref="IClassificationType"/> objects for the <c>Blue print</c> language.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v24.1.1.0 (http://www.actiprosoftware.com).
    /// Generated code is based on input created by Blueprint.
    /// Blueprint
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("LanguageDesigner", "24.1.1.0")]
    public interface IBlueClassificationTypeProvider {
        
        /// <summary>
        /// Gets the <c>Brackets</c> classification type.
        /// </summary>
        /// <value>The <c>Brackets</c> classification type.</value>
        IClassificationType Brackets {
            get;
        }
        
        /// <summary>
        /// Gets the <c>Column</c> classification type.
        /// </summary>
        /// <value>The <c>Column</c> classification type.</value>
        IClassificationType Column {
            get;
        }
        
        /// <summary>
        /// Gets the <c>Comment</c> classification type.
        /// </summary>
        /// <value>The <c>Comment</c> classification type.</value>
        IClassificationType Comment {
            get;
        }
        
        /// <summary>
        /// Gets the <c>Delimiter</c> classification type.
        /// </summary>
        /// <value>The <c>Delimiter</c> classification type.</value>
        IClassificationType Delimiter {
            get;
        }
        
        /// <summary>
        /// Gets the <c>Identifier</c> classification type.
        /// </summary>
        /// <value>The <c>Identifier</c> classification type.</value>
        IClassificationType Identifier {
            get;
        }
        
        /// <summary>
        /// Gets the <c>InterpolatedStringDelimiter</c> classification type.
        /// </summary>
        /// <value>The <c>InterpolatedStringDelimiter</c> classification type.</value>
        IClassificationType InterpolatedStringDelimiter {
            get;
        }
        
        /// <summary>
        /// Gets the <c>Keyword</c> classification type.
        /// </summary>
        /// <value>The <c>Keyword</c> classification type.</value>
        IClassificationType Keyword {
            get;
        }
        
        /// <summary>
        /// Gets the <c>Number</c> classification type.
        /// </summary>
        /// <value>The <c>Number</c> classification type.</value>
        IClassificationType Number {
            get;
        }
        
        /// <summary>
        /// Gets the <c>Parenthesis</c> classification type.
        /// </summary>
        /// <value>The <c>Parenthesis</c> classification type.</value>
        IClassificationType Parenthesis {
            get;
        }
        
        /// <summary>
        /// Gets the <c>String</c> classification type.
        /// </summary>
        /// <value>The <c>String</c> classification type.</value>
        IClassificationType String {
            get;
        }
    }
}
