<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore.Microsoft" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Blueprint.Core.Domain\Blueprint.Core.Domain.csproj" />
    <ProjectReference Include="..\Blueprint.Core.Application\Blueprint.Core.Application.csproj" />
  </ItemGroup>
</Project>